/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.actividad5_ejercicio1;

import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.lang.NumberFormatException;
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class Principal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        btnRead = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        btnCleanFields = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nombre");

        jLabel2.setText("Numero");

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        btnRead.setText("Read");
        btnRead.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReadActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnCleanFields.setText("Clean Fields");
        btnCleanFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCleanFieldsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(txtNombre)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(btnCreate)
                        .addGap(18, 18, 18)
                        .addComponent(btnRead)
                        .addGap(18, 18, 18)
                        .addComponent(btnUpdate)
                        .addGap(31, 31, 31)
                        .addComponent(btnDelete)
                        .addGap(18, 18, 18)
                        .addComponent(btnCleanFields)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreate)
                    .addComponent(btnRead)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnCleanFields))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
     try {
        String newName = String.valueOf(txtNombre.getText());
        long newNumber = Long.parseLong(txtNumero.getText());
        
        String nameNumberString;
        String name;
        long number;
        int index;
        
        File file = new File("C:\\Users\\Asus\\Documents\\NetBeansProjects\\ACTIVIDAD5_EJERCICIO1\\friendsContact.txt");
        
        if (!file.exists()) {
            file.createNewFile();
        }

        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;
        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();
            String[] lineSplit = nameNumberString.split("!");
            name = lineSplit[0];
            number = Long.parseLong(lineSplit[1]);

            if (name.equals(newName) || number == newNumber) { 
                found = true;
                break;
            }
        }

        if (!found) {
            nameNumberString = newName + "!" + newNumber;
            raf.writeBytes(nameNumberString + System.lineSeparator());
           
            JOptionPane.showMessageDialog(null, "Friend added");
            txtNombre.setText("");
            txtNumero.setText("");
            
        } else {
            JOptionPane.showMessageDialog(null, "Input name already exists.");
            txtNombre.setText("");
            txtNumero.setText("");
        }

        raf.close();

    } catch (IOException ioe) {
        System.out.println(ioe);
        JOptionPane.showMessageDialog(null, "An error has ocurred creating/opening the file.");
        
    } catch (NumberFormatException nef) {
        System.out.println(nef);
        JOptionPane.showMessageDialog(null, "A number format has ocurred.");
    }

    }//GEN-LAST:event_btnCreateActionPerformed

    private void btnReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReadActionPerformed
try {
        String nameNumberString;
        String name;
        long number;

        File file = new File("C:\\Users\\Asus\\Documents\\NetBeansProjects\\ACTIVIDAD5_EJERCICIO1\\friendsContact.txt");

        if (!file.exists()) {
            JOptionPane.showMessageDialog(null, "No contacts found (file does not exist).");
            return;
        }

        RandomAccessFile raf = new RandomAccessFile(file, "r");

        StringBuilder data = new StringBuilder();

        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();

            if (nameNumberString == null || nameNumberString.trim().isEmpty()) {
                continue;
            }

            String[] lineSplit = nameNumberString.split("!");
            if (lineSplit.length < 2) continue;

            name = lineSplit[0];
            number = Long.parseLong(lineSplit[1]);

            data.append("Friend Name: ").append(name).append("\n")
                .append("Contact Number: ").append(number).append("\n\n");
        }

        raf.close();

        if (data.length() == 0) {
            JOptionPane.showMessageDialog(null, "No contacts to display.");
        } else {
            JOptionPane.showMessageDialog(null, data.toString());
        }

    } catch (IOException ioe) {
        ioe.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error reading the file.");
    } catch (NumberFormatException nef) {
        nef.printStackTrace();
        JOptionPane.showMessageDialog(null, "Invalid number format in file.");
    }








    }//GEN-LAST:event_btnReadActionPerformed

    private void btnCleanFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCleanFieldsActionPerformed
       txtNombre.setText("");
       txtNumero.setText("");
    }//GEN-LAST:event_btnCleanFieldsActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                                         
    try {
        String newName = txtNombre.getText();
        long newNumber = Long.parseLong(txtNumero.getText());

        String nameNumberString;
        String name;
        long number;
        int index;

        File file = new File("C:\\Users\\Asus\\Documents\\NetBeansProjects\\ACTIVIDAD5_EJERCICIO1\\friendsContact.txt");

        if (!file.exists()) {
            file.createNewFile();
        }

        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;

        // Buscar si existe
        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();
            String[] lineSplit = nameNumberString.split("!");
            name = lineSplit[0];
            number = Long.parseLong(lineSplit[1]);

            if (name.equals(newName)) {
                found = true;
                break;
            }
        }

        if (found) {
            File tmpFile = new File("temp.txt");
            RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");

            raf.seek(0);

            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();
                index = nameNumberString.indexOf('!');
                name = nameNumberString.substring(0, index);

                if (name.equals(newName)) {
                    nameNumberString = name + "!" + newNumber;
                }

                tmpraf.writeBytes(nameNumberString + System.lineSeparator());
            }

            raf.seek(0);
            tmpraf.seek(0);

            while (tmpraf.getFilePointer() < tmpraf.length()) {
                raf.writeBytes(tmpraf.readLine() + System.lineSeparator());
            }

            raf.setLength(tmpraf.length());

            tmpraf.close();
            raf.close();
            tmpFile.delete();

            JOptionPane.showMessageDialog(null, "Friend updated.");
        } else {
            raf.close();
            JOptionPane.showMessageDialog(null, "The name does not exist.");
        }

    } catch (IOException ioe) {
        ioe.printStackTrace();
        JOptionPane.showMessageDialog(null, "File error.");
    } catch (NumberFormatException nef) {
        nef.printStackTrace();
        JOptionPane.showMessageDialog(null, "Invalid number format.");
    }

            
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
        String deleteName = txtNombre.getText().trim();

        if (deleteName.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Enter a name to delete.");
            return;
        }

        String nameNumberString;
        String name;
        long number;
        int index;

        File file = new File("C:\\Users\\Asus\\Documents\\NetBeansProjects\\ACTIVIDAD5_EJERCICIO1\\friendsContact.txt");

        if (!file.exists()) {
            JOptionPane.showMessageDialog(null, "File does not exist.");
            return;
        }

        RandomAccessFile raf = new RandomAccessFile(file, "rw");
        boolean found = false;

        // Buscar si el contacto existe
        while (raf.getFilePointer() < raf.length()) {
            nameNumberString = raf.readLine();
            String[] parts = nameNumberString.split("!");
            name = parts[0];
            number = Long.parseLong(parts[1]);

            if (name.equals(deleteName)) {
                found = true;
                break;
            }
        }

        if (found) {

            File tmpFile = new File("temp.txt");
            RandomAccessFile tmpraf = new RandomAccessFile(tmpFile, "rw");

            // Volver al inicio del archivo
            raf.seek(0);

            while (raf.getFilePointer() < raf.length()) {
                nameNumberString = raf.readLine();
                index = nameNumberString.indexOf('!');
                name = nameNumberString.substring(0, index);

                // Si es el contacto a eliminar, NO se copia
                if (name.equals(deleteName)) {
                    continue;
                }

                // Copiar contacto que no fue eliminado
                tmpraf.writeBytes(nameNumberString + System.lineSeparator());
            }

            // Copiar del temporal al original
            raf.seek(0);
            tmpraf.seek(0);

            while (tmpraf.getFilePointer() < tmpraf.length()) {
                raf.writeBytes(tmpraf.readLine() + System.lineSeparator());
            }

            // Ajustar tamaño del archivo original
            raf.setLength(tmpraf.length());

            tmpraf.close();
            raf.close();
            tmpFile.delete();

            JOptionPane.showMessageDialog(null, "Friend deleted.");
            txtNombre.setText("");
            txtNumero.setText("");

        } else {
            raf.close();
            JOptionPane.showMessageDialog(null, "Name does not exist.");
        }

    } catch (IOException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(null, "An error occurred.");
    }
    }//GEN-LAST:event_btnDeleteActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCleanFields;
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnRead;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
